export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";
export const SET_SELECTED = "SET_SELECTED";
export const FETCH_CHECKLIST = "FETCH_CHECKLIST";
export const FETCH_DOCUMENTS_SUCCESS = "FETCH_DOCUMENTS_SUCCESS";
export const FETCH_DOCUMENTS_REQUEST = "FETCH_DOCUMENTS_REQUEST";
